"use client";

import { Search, SlidersHorizontal, X } from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useMemo } from "react";

import { ProductCard } from "@/components/store/product-card";
import { getProductSellingPrice } from "@/lib/utils/pricing";
import type { Brand, Category, Product } from "@/types";

export function Catalog({ products, brands, categories }: { products: Product[]; brands: Brand[]; categories: Category[] }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const search = params.get("search") ?? ""; const brand = params.get("brand") ?? ""; const category = params.get("category") ?? ""; const sort = params.get("sort") ?? "recommended";
  const update = (key: string, value: string) => { const next = new URLSearchParams(params.toString()); if (value) next.set(key, value); else next.delete(key); router.replace(`${pathname}?${next.toString()}`, { scroll: false }); };
  const filtered = useMemo(() => {
    const normalized = search.trim().toLocaleLowerCase("es");
    return products.filter((product) => (!normalized || `${product.name} ${product.brand.name} ${product.category.name}`.toLocaleLowerCase("es").includes(normalized)) && (!brand || product.brand.slug === brand) && (!category || product.category.slug === category)).toSorted((a, b) => { if (sort === "name") return a.name.localeCompare(b.name, "es"); if (sort === "price-asc") return getProductSellingPrice(a) - getProductSellingPrice(b); if (sort === "price-desc") return getProductSellingPrice(b) - getProductSellingPrice(a); return Number(b.featured) - Number(a.featured); });
  }, [products, search, brand, category, sort]);
  const active = Boolean(search || brand || category || sort !== "recommended");
  return <div><div className="surface-card mb-8 grid gap-3 rounded-[1.5rem] p-4 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><label className="relative"><span className="sr-only">Buscar por nombre</span><Search className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted" /><input className="field pl-11" value={search} onChange={(event) => update("search", event.target.value)} placeholder="¿Qué estás buscando?" /></label><label><span className="sr-only">Filtrar por categoría</span><select className="select-field" value={category} onChange={(event) => update("category", event.target.value)}><option value="">Todas las categorías</option>{categories.map((item) => <option value={item.slug} key={item.id}>{item.name}</option>)}</select></label><label><span className="sr-only">Filtrar por marca</span><select className="select-field" value={brand} onChange={(event) => update("brand", event.target.value)}><option value="">Todas las marcas</option>{brands.map((item) => <option value={item.slug} key={item.id}>{item.name}</option>)}</select></label><label><span className="sr-only">Ordenar</span><select className="select-field" value={sort} onChange={(event) => update("sort", event.target.value)}><option value="recommended">Recomendados</option><option value="name">Nombre A–Z</option><option value="price-asc">Precio menor</option><option value="price-desc">Precio mayor</option></select></label></div><div className="mb-6 flex items-center justify-between gap-4"><p className="flex items-center gap-2 text-sm font-bold"><SlidersHorizontal className="size-4 text-primary" />{filtered.length} {filtered.length === 1 ? "producto" : "productos"}</p>{active ? <button type="button" className="flex items-center gap-1 text-xs font-bold text-primary" onClick={() => router.replace(pathname)}><X className="size-4" />Limpiar filtros</button> : null}</div>{filtered.length ? <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4 md:gap-5">{filtered.map((product, index) => <ProductCard product={product} index={index} key={product.id} />)}</div> : <div className="rounded-[2rem] border border-dashed border-border bg-surface px-6 py-20 text-center"><Search className="mx-auto size-10 text-muted" /><h2 className="display mt-4 text-3xl font-bold">No encontramos coincidencias</h2><p className="mt-2 text-sm text-muted">Prueba otra palabra o limpia los filtros para volver a explorar.</p><button type="button" className="button-primary mt-5" onClick={() => router.replace(pathname)}>Limpiar filtros</button></div>}</div>;
}
