import Link from "next/link";
import { ArrowRight, Check, MessageCircle, Search, Send, ShoppingBag, Sparkles } from "lucide-react";

import { ProductCard } from "@/components/store/product-card";
import { getStoreData } from "@/lib/data/store";

const steps = [
  { icon: Search, title: "Elige", text: "Explora productos y ofertas." },
  { icon: ShoppingBag, title: "Reúne", text: "Agrega todo lo que te guste." },
  { icon: Send, title: "Solicita", text: "Envíanos tu pedido sin pagar." },
  { icon: Check, title: "Revisamos", text: "Confirmamos disponibilidad real." },
  { icon: MessageCircle, title: "Hablamos", text: "Te contactamos por WhatsApp." },
];

export default async function HomePage() {
  const { products, categories, brands, isDemo } = await getStoreData();
  const featured = products.filter((product) => product.featured).slice(0, 4);
  const fair = products.filter((product) => product.pricing_type === "FAIR").slice(0, 4);
  return (
    <>
      {isDemo ? <div className="border-b border-[#ead7a8] bg-[#fff6dc] px-4 py-2 text-center text-xs font-semibold text-[#7e5a1d]">Vista de demostración · Conecta Supabase para gestionar datos y recibir pedidos reales.</div> : null}
      <section className="relative overflow-hidden bg-[#eee9df]"><div className="container-page grid min-h-[650px] items-center gap-10 py-16 md:grid-cols-[1.03fr_.97fr] md:py-20"><div className="relative z-10 reveal"><p className="eyebrow mb-5 text-primary">Edición de feria · Agosto</p><h1 className="display max-w-3xl text-balance text-[clamp(3.4rem,8vw,7.3rem)] font-semibold leading-[.79] tracking-[-.045em] text-secondary">Hallazgos que <span className="italic text-primary">iluminan</span> lo cotidiano.</h1><p className="mt-7 max-w-xl text-base leading-7 text-muted md:text-lg">Perfumería, bienestar, hogar y accesorios seleccionados con cariño. Arma tu pedido y confirmamos cada pieza contigo por WhatsApp.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="button-primary">Explorar la feria <ArrowRight className="size-4" /></Link><Link href="#como-funciona" className="button-ghost">¿Cómo funciona?</Link></div><div className="mt-9 flex items-center gap-3 text-xs font-bold text-muted"><span className="grid size-8 place-items-center rounded-full bg-secondary text-white"><Check className="size-4" /></span>Sin pagos en línea · Atención humana</div></div><div className="relative mx-auto aspect-[4/4.7] w-[min(88%,480px)] reveal"><div className="absolute inset-[7%_2%_2%_10%] rotate-3 rounded-[45%_45%_3rem_3rem] bg-primary shadow-2xl" /><div className="product-art product-art-1 absolute inset-[0_10%_8%_0] -rotate-3 overflow-hidden rounded-[45%_45%_3rem_3rem] border-[10px] border-surface shadow-2xl"><Sparkles className="absolute left-1/2 top-[38%] z-10 size-20 -translate-x-1/2 text-white/80" strokeWidth={1} /><div className="absolute bottom-9 left-1/2 z-10 w-[74%] -translate-x-1/2 rounded-2xl bg-surface/90 p-4 text-center backdrop-blur"><p className="eyebrow text-primary">Selección Lúmina</p><p className="display text-2xl font-bold">Bonito. Especial. Para ti.</p></div></div><div className="absolute -right-2 top-[18%] z-20 rounded-2xl bg-accent p-4 shadow-xl"><span className="display block text-3xl font-bold">hasta 35%</span><span className="text-[.6rem] font-extrabold uppercase tracking-widest">precio feria</span></div></div></div></section>

      <section className="container-page py-20" id="categories"><div className="mb-9 flex items-end justify-between gap-5"><div><p className="eyebrow text-primary">Encuentra tu próximo favorito</p><h2 className="display mt-2 text-4xl font-bold md:text-5xl">Explora por categoría</h2></div><Link href="/products" className="hidden items-center gap-2 text-sm font-bold text-primary md:flex">Ver todas <ArrowRight className="size-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{categories.map((category, index) => <Link key={category.id} href={`/products?category=${category.slug}`} className={`group relative min-h-48 overflow-hidden rounded-[1.6rem] p-5 text-white product-art product-art-${index % 5}`}><span className="relative z-10 flex h-full flex-col justify-end"><span className="display text-2xl font-bold">{category.name}</span><span className="mt-1 text-xs text-white/75">{category.description}</span><ArrowRight className="mt-4 size-5 transition group-hover:translate-x-1" /></span></Link>)}</div></section>

      <section className="bg-surface py-20"><div className="container-page"><div className="mb-9 md:flex md:items-end md:justify-between"><div><p className="eyebrow text-primary">Curaduría de la semana</p><h2 className="display mt-2 text-4xl font-bold md:text-5xl">Favoritos de la feria</h2></div><p className="mt-3 max-w-md text-sm leading-6 text-muted">Una selección cambiante de piezas que nos encantan y creemos que a ti también.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-5">{featured.map((product, index) => <ProductCard product={product} index={index} key={product.id} />)}</div></div></section>

      <section className="container-page py-20"><div className="overflow-hidden rounded-[2rem] bg-secondary p-7 text-white md:p-12"><div className="mb-10 grid gap-4 md:grid-cols-2"><div><p className="eyebrow text-accent">Precios que dan gusto</p><h2 className="display mt-2 text-4xl font-bold md:text-5xl">Ofertas de feria</h2></div><p className="self-end text-sm leading-6 text-white/65">Compara el precio de catálogo y descubre el precio especial. La disponibilidad se valida al recibir tu solicitud.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{fair.map((product, index) => <ProductCard product={product} index={index + 2} key={product.id} />)}</div></div></section>

      <section id="como-funciona" className="bg-[#ebe4d8] py-20"><div className="container-page"><div className="mx-auto mb-12 max-w-2xl text-center"><p className="eyebrow text-primary">Cercano y sencillo</p><h2 className="display mt-2 text-4xl font-bold md:text-5xl">De tu pantalla a tus manos</h2><p className="mt-3 text-sm leading-6 text-muted">Enviar la solicitud no garantiza disponibilidad inmediata. Revisamos cada producto y te confirmamos personalmente.</p></div><div className="grid gap-3 md:grid-cols-5">{steps.map((step, index) => <div className="relative rounded-2xl border border-border bg-surface p-5" key={step.title}><span className="mb-8 grid size-11 place-items-center rounded-full bg-secondary text-white"><step.icon className="size-5" /></span><span className="absolute right-4 top-4 display text-3xl text-border">0{index + 1}</span><h3 className="display text-2xl font-bold">{step.title}</h3><p className="mt-2 text-xs leading-5 text-muted">{step.text}</p></div>)}</div></div></section>

      <section className="container-page py-20"><div className="text-center"><p className="eyebrow text-primary">Marcas para descubrir</p><h2 className="display mt-2 text-4xl font-bold">Nombres con personalidad</h2></div><div className="mt-10 flex flex-wrap items-center justify-center gap-x-12 gap-y-7">{brands.map((brand) => <Link key={brand.id} href={`/products?brand=${brand.slug}`} className="display text-3xl font-bold text-secondary/70 transition hover:text-primary">{brand.name}</Link>)}</div></section>
    </>
  );
}