"use client";

import Link from "next/link";
import { EyeOff, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

import { PriceDisplay } from "@/components/store/price-display";
import { ProductImage } from "@/components/store/product-image";
import type { Brand, Category, Product } from "@/types";

export function ProductAdminList({ initialProducts, brands, categories }: { initialProducts: Product[]; brands: Brand[]; categories: Category[] }) {
  const [products, setProducts] = useState(initialProducts); const [search, setSearch] = useState(""); const [brand, setBrand] = useState(""); const [category, setCategory] = useState("");
  const filtered = useMemo(() => products.filter((product) => (!search || `${product.name} ${product.brand.name} ${product.category.name}`.toLowerCase().includes(search.toLowerCase())) && (!brand || product.brand_id === brand) && (!category || product.category_id === category)), [products, search, brand, category]);
  const toggleActive = async (product: Product) => { const response = await fetch(`/api/admin/products/${product.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...product, active: !product.active, brand: undefined, category: undefined }) }); if (!response.ok) return toast.error("No pudimos guardar los cambios."); setProducts((current) => current.map((item) => item.id === product.id ? { ...item, active: !item.active } : item)); toast.success(product.active ? "Producto desactivado." : "Producto activado."); };
  const remove = async (product: Product) => { if (!window.confirm(`¿Eliminar “${product.name}”? Si tiene historial, solamente se desactivará.`)) return; const response = await fetch(`/api/admin/products/${product.id}`, { method: "DELETE" }); const result = await response.json() as { deactivated?: boolean; message?: string }; if (!response.ok) return toast.error(result.message ?? "No pudimos eliminar el producto."); if (result.deactivated) { setProducts((current) => current.map((item) => item.id === product.id ? { ...item, active: false } : item)); toast.success("El producto tiene historial y fue desactivado."); } else { setProducts((current) => current.filter((item) => item.id !== product.id)); toast.success("Producto eliminado."); } };
  return <><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-primary">Catálogo</p><h1 className="display mt-2 text-4xl font-bold md:text-5xl">Productos</h1><p className="mt-2 text-sm text-muted">{products.length} productos registrados</p></div><Link href="/admin/products/new" className="button-primary"><Plus className="size-4" />Nuevo producto</Link></div><div className="mb-5 grid gap-3 rounded-2xl border border-border bg-surface p-4 md:grid-cols-[1.5fr_1fr_1fr]"><label className="relative"><span className="sr-only">Buscar</span><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted" /><input className="field pl-11" placeholder="Buscar producto…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select className="select-field" value={brand} onChange={(event) => setBrand(event.target.value)}><option value="">Todas las marcas</option>{brands.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select className="select-field" value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Todas las categorías</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><div className="overflow-hidden rounded-2xl border border-border bg-surface"><div className="divide-y divide-border">{filtered.map((product, index) => <article key={product.id} className={`grid grid-cols-[64px_1fr_auto] items-center gap-3 p-3 md:grid-cols-[72px_1.5fr_1fr_1fr_auto] md:p-4 ${!product.active ? "opacity-55" : ""}`}><div className="relative aspect-square overflow-hidden rounded-xl"><ProductImage src={product.image_url} alt="" artIndex={index} /></div><div className="min-w-0"><p className="truncate font-bold">{product.name}</p><p className="text-xs text-muted md:hidden">{product.brand.name} · {product.category.name}</p><PriceDisplay product={product} compact /></div><span className="hidden text-sm md:block">{product.brand.name}</span><span className="hidden text-sm md:block">{product.category.name}</span><div className="flex items-center justify-end gap-1"><button type="button" onClick={() => toggleActive(product)} className="focus-ring rounded-lg p-2 text-muted hover:text-primary" aria-label={product.active ? "Desactivar" : "Activar"}><EyeOff className="size-4" /></button><Link href={`/admin/products/${product.id}/edit`} className="focus-ring rounded-lg p-2 text-muted hover:text-primary" aria-label="Editar"><Pencil className="size-4" /></Link><button type="button" onClick={() => remove(product)} className="focus-ring rounded-lg p-2 text-muted hover:text-destructive" aria-label="Eliminar"><Trash2 className="size-4" /></button></div></article>)}{!filtered.length ? <div className="p-14 text-center text-sm text-muted">No hay productos que coincidan con los filtros.</div> : null}</div></div></>;
}
