import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleX, Clock3, Package, ShoppingBag } from "lucide-react";

import { OrderStatusBadge } from "@/components/shared/order-status-badge";
import { getAdminOrders, getAdminProducts } from "@/lib/data/admin";
import { formatMoney } from "@/lib/utils/pricing";

export default async function AdminDashboardPage() {
  const [orders, products] = await Promise.all([getAdminOrders(), getAdminProducts()]);
  const cards = [{ label: "Productos activos", value: products.filter((p) => p.active).length, icon: Package, tone: "bg-[#ebe3d3] text-[#82612d]" }, { label: "Pedidos totales", value: orders.length, icon: ShoppingBag, tone: "bg-[#e0e8ef] text-[#385a76]" }, { label: "Pedidos nuevos", value: orders.filter((o) => o.status === "NEW").length, icon: Clock3, tone: "bg-[#fff0ca] text-[#855a0e]" }, { label: "Confirmados", value: orders.filter((o) => o.status === "CONFIRMED").length, icon: CheckCircle2, tone: "bg-[#dff1e7] text-success" }, { label: "Cancelados", value: orders.filter((o) => o.status === "CANCELLED").length, icon: CircleX, tone: "bg-[#fae1df] text-destructive" }];
  return <><header className="mb-8"><p className="eyebrow text-primary">Resumen de hoy</p><h1 className="display mt-2 text-4xl font-bold md:text-5xl">Todo bajo control</h1><p className="mt-2 text-sm text-muted">Revisa el estado de la feria y atiende primero las solicitudes nuevas.</p></header><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map((card) => <div key={card.label} className="rounded-2xl border border-border bg-surface p-5"><span className={`grid size-10 place-items-center rounded-xl ${card.tone}`}><card.icon className="size-5" /></span><p className="display mt-5 text-4xl font-bold">{card.value}</p><p className="mt-1 text-xs font-bold text-muted">{card.label}</p></div>)}</section><section className="mt-8 overflow-hidden rounded-2xl border border-border bg-surface"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="display text-2xl font-bold">Pedidos recientes</h2><p className="text-xs text-muted">Últimas solicitudes recibidas</p></div><Link href="/admin/orders" className="flex items-center gap-2 text-xs font-bold text-primary">Ver todos <ArrowRight className="size-4" /></Link></div><div className="divide-y divide-border">{orders.slice(0, 6).map((order) => <Link href={`/admin/orders/${order.id}`} key={order.id} className="grid gap-3 p-5 transition hover:bg-[#f7f3ed] sm:grid-cols-[1fr_1.2fr_auto_auto] sm:items-center"><strong>{order.order_number}</strong><span className="text-sm">{order.first_name} {order.last_name}</span><OrderStatusBadge status={order.status} /><strong className="text-sm">{formatMoney(order.total)}</strong></Link>)}</div></section></>;
}
